version: 2
updates:
  # Enable version updates for npm (Frontend)
  - package-ecosystem: "npm"
    directory: "/cms-1.0"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"

  # Enable version updates for Composer (Backend)
  - package-ecosystem: "composer"
    directory: "/BE-1.0"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"

